### ISSUE TITLE
juliet.html is deprecated and should be removed

### ISSUE THREAD

**Issue by bobbydilley** [theooos/theooos.github.io#1]
It is currently unsafe to use juliet.html in a production environment.

**Comment by Quackmatic** [comment]
![11870878_869166716501690_8881522219963962411_n](https://cloud.githubusercontent.com/assets/3249226/17078108/4e09a200-50e1-11e6-8b24-7ce81cd32ba8.jpg)

**Comment by theooos** [comment]
Bug has been resolved. Many blessings.
